spring:
  jpa:
    show-sql: true

logging:
  level:
    com.cloudprocessing: DEBUG
    org.springframework.security: DEBUG
    org.flywaydb: DEBUG

app:
  s3:
    endpoint: ${AWS_ENDPOINT_URL:http://localhost:4566}          # LocalStack (internal)
    presigned-endpoint: ${APP_S3_PRESIGNED-ENDPOINT:http://localhost:4566}  # public-facing
